Repository bhagatabhijeet/chype, pull requests merged in 2020-11, with the labels that each got.

#7 add mainpage and update packages
  client/package-lock.json
  client/package.json
  client/src/assets/images/.gitkeep
  client/src/assets/styles/.gitkeep
  client/src/components/.gitkeep
  client/src/index.js
  client/src/pages/MainPage.jsx
Labels: Project Task

#8 create first page and sign up,log in form
  client/public/images/cccc.jpg
  client/public/images/chype Logo3.png
  client/public/images/chype.png
  client/src/App.js
  client/src/pages/LandingPage/Background.js
  client/src/pages/index.js
  package.json
Labels: Project Task

#9 add signup.jsx
  client/src/index.js
  client/src/pages/SignUp.jsx
Labels: Project Task

#10 add unfinished MainPage LoggedInUserCard and Navbar
  client/src/components/LoggedInUserCard.jsx
  client/src/components/Navbar.jsx
  client/src/pages/MainPage.jsx
Labels: Project Task

#11 backend changes
  controllers/authController.js
  controllers/messageController.js
  controllers/roomController.js
  controllers/userController.js
  middlewares/authMiddlewares.js
  middlewares/authorizationMiddleware.js
  middlewares/signInMiddleware.js
  model/userOrm.js
  model/userQueries.js
  models/Message.js
  models/Room.js
  models/User.js
  models/index.js
  package-lock.json
  package.json
  routes/apiRoutes/authRoutes/index.js
  routes/apiRoutes/index.js
  routes/apiRoutes/messageRoutes/index.js
  routes/apiRoutes/userRoutes.js
  routes/apiRoutes/userRoutes/index.js
  routes/authRoutes/index.js
  routes/index.js
  sengridSample.js
  services/passport.js
Labels: Project Task

#12 create basic chat functionality on main page using socket.oi
  .idea/.gitignore
  .idea/chype.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dbnavigator.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  client/package.json
  client/src/App.js
  client/src/pages/MainPage.jsx
  index.js
  package-lock.json
  package.json
Labels: Project Task

#13 add images and enhance signin and add footer
  client/public/Logo.jpg
  client/public/chype-favicon.ico
  client/public/chype-favicon.png
  client/public/chypeLogo-trans.png
  client/public/chypeShortLogo-border.jpg
  client/public/chypeShortLogo-trans.ico
  client/public/chypeShortLogo-trans.png
  client/public/chypeShortLogo.jpg
  client/public/images/multilingual-support.jpg
  client/public/index.html
  client/public/logo192-old.png
  client/src/assets/images/chypeLogo-trans.png
  client/src/assets/images/chypeShortLogo-trans.png
  client/src/assets/images/multilingual-support.jpg
  client/src/assets/images/signInBg.jpg
  client/src/components/Footer.jsx
  client/src/index.js
  client/src/pages/SignInPage.jsx
  db/Connecting toMongoDB Using Robo3t.docx
  sengridSample.js
Labels: Project Task

#14 Abhi
  index.js
  package.json
Labels: enhancement

#15 create sign up page
  client/src/pages/LanguOption.jsx
Labels: Project Task

#17 Setare
  client/src/App.css
  client/src/pages/SignUp.jsx
Labels: Project Task

#18 Setare
  client/package-lock.json
  client/package.json
Labels: Project Task

#19 remove the react-bootstrap form import
  client/src/index.js
  client/src/pages/SignUp.jsx
Labels: bug

#20 add react scripts to package.json including the heroku post build
  package-lock.json
  package.json
Labels: Project Task

#22 remove manifest link
  client/public/index.html
Labels: CleanUp

#23 add trailing slash to the proxy and proxy is required only in client
  client/package.json
  package.json
Labels: CleanUp

#24 package changes
  client/package-lock.json
  package.json
Labels: CleanUp

#25 resolve errors that got in because of merge conflicts
  index.js
Labels: CleanUp, bug

#26 link sign in and signup pages
  client/src/index.js
  client/src/pages/SignInPage.jsx
  client/src/pages/SignUpNew.jsx
Labels: enhancement
