Repository bhagatabhijeet/chype, pull requests merged in 2020-12, with the labels that each got.

#29 make the size of logo small so that whole form fits on the small screen
  client/src/pages/SignUpNew.jsx
Labels: CleanUp

#30 add badge for avatar and change style for logged in user card
  client/src/components/LoggedInUserCard.jsx
Labels: Project Task

#31 create menuBar for settings and sign out
  client/src/components/FullScreenSetting.jsx
  client/src/components/LoggedInUserCard.jsx
  client/src/components/Menu.jsx
  client/src/index.js
Labels: Project Task

#37 create setting and signout page
  client/src/components/FullScreenSetting.jsx
  client/src/components/LoggedInUserCard.jsx
  client/src/components/Menu.jsx
  client/src/index.js
  client/src/pages/SettingsPage.jsx
Labels: Project Task

#39 make settings collapse and create account and general component
  client/src/components/Account.jsx
  client/src/components/General.jsx
  client/src/pages/SettingsPage.jsx
Labels: Project Task

#41 homepage, homepage footer and sign up changes
  client/package-lock.json
  client/package.json
  client/src/assets/images/chypeLogo-trans.png
  client/src/components/HomePageFooter.jsx
  client/src/index.js
  client/src/pages/HomePage.jsx
  client/src/pages/SignUpNew.jsx
Labels: Project Task

#43 add language to general component
  client/package.json
  client/src/components/Account.jsx
  client/src/components/ChooseLangu.jsx
  client/src/components/General.jsx
  client/src/components/Menu.jsx
  client/src/pages/SettingsPage.jsx
Labels: Project Task

#47 resolve the responsiveness of footer and near final draft of homepage
  client/src/App.css
  client/src/assets/images/fun_animation.gif
  client/src/components/HomePageFooter.jsx
  client/src/pages/HomePage.jsx
Labels: Project Task

#48 add common.css and add 'i want to become chyper' button
  client/src/assets/styles/common.css
  client/src/pages/HomePage.jsx
Labels: Project Task

#50 Add sign up form validations
  client/src/assets/images/signup-background.jpg
  client/src/pages/SignUpNew.jsx
Labels: Project Task

#52 deleted old sign up and hooked up signup page with the api call
  client/src/pages/SignUp.jsx
  client/src/pages/SignUpNew.jsx
  controllers/authController.js
  db/mongoDBConnection.js
Labels: Project Task

#53 create appBar component for home page
  client/src/components/AppBarMain.jsx
  client/src/pages/HomePage.jsx
Labels: Project Task

#55 rename SignUpNew to signup
  client/src/index.js
  client/src/pages/SignUpNew.jsx
Labels: Project Task

#56 add renamed singup.jsx
  client/src/pages/SignUp.jsx
Labels: Project Task

#57 add props and colored logo to AppBar, add appbar to homepage and signup
  client/src/assets/images/new_inverse_trans_blue.png
  client/src/components/AppBarMain.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/SignUp.jsx
Labels: Project Task

#59 add home link to logo in app bar
  client/src/components/AppBarMain.jsx
  client/src/components/animated/Parallax.jsx
Labels: Project Task

#60 move authroutes out of /api thus making auth routes as /auth
  routes/apiRoutes/index.js
  routes/authRoutes/index.js
  routes/index.js
Labels: enhancement

#61 resolve all react errors and warnings
  client/src/assets/styles/parallax.css
  client/src/components/Account.jsx
  client/src/components/AppBarMain.jsx
  client/src/components/General.jsx
  client/src/components/LoggedInUserCard.jsx
  client/src/components/animated/Parallax.jsx
  client/src/pages/SignInNew.jsx
  client/src/pages/SignInPage.jsx
  client/src/pages/SignUp.jsx
Labels: CleanUp

#62 bring app.js back again, rename app.js to app.jsx , add protectedRout…
  .vscode/launch.json
  client/src/App.js
  client/src/App.jsx
  client/src/index.js
  client/src/pages/MainPage.jsx
  client/src/pages/ProtectedRoutes.jsx
  client/src/pages/SignInNew.jsx
  controllers/authController.js
  db/mongoDBConnection.js
  models/User.js
Labels: enhancement

#63 add redux toolkit dependency and change app /main route to not use us…
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/redux/index.js
Labels: enhancement

#65 add react-redux as dependency, add UserReducer
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/index.js
  client/src/redux/UserReducer.js
  client/src/redux/index.js
Labels: enhancement

#68 add redux persist
  client/package-lock.json
  client/package.json
  client/src/components/LoggedInUserCard.jsx
  client/src/index.js
  client/src/redux/index.js
Labels: Project Task

#69 change storage to session storage
  client/src/redux/index.js
Labels: enhancement

#72 main page layout changes
  client/src/components/ChatTopNav.jsx
  client/src/components/LoggedInUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/pages/MainPage.jsx
Labels: Project Task

#73 more layout changes
  client/src/components/UsersBox.jsx
  client/src/pages/MainPage.jsx
Labels: Project Task

#76 create divbar component for message
  client/src/components/divBar/DivBar.css
  client/src/components/divBar/DivBar.jsx
Labels: Project Task

#78 fix sign up button
  client/src/pages/SignInNew.jsx
Labels: Project Task

#80 signout completed
  client/src/components/LoggedInUserCard.jsx
Labels: enhancement

#81 resolve state issues for signout
  client/src/components/LoggedInUserCard.jsx
Labels: bug

#82 change background color when only on main page
  client/src/pages/MainPage.jsx
Labels: enhancement

#84 change width of userontainer to 30%
  client/src/components/ChatContainer.jsx
  client/src/components/FriendUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/components/UsersContainer.jsx
Labels: enhancement

#85 make userRoute more modular
  controllers/userController.js
  routes/apiRoutes/index.js
  routes/apiRoutes/userRoutes/index.js
Labels: enhancement

#86 cleanse MainPage and arrange the controls to proper containers
  client/src/components/ChatContainer.jsx
  client/src/components/FriendUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/components/UsersContainer.jsx
  client/src/pages/MainPage.jsx
Labels: CleanUp

#87 resolve the filterme bug
  controllers/userController.js
Labels: bug

#89 remove duplicate app.use and in userbox.jsx handle if q is empty
  .vscode/launch.json
  client/src/components/UsersBox.jsx
  index.js
Labels: CleanUp

#90 complete basic coloring and add characters left span
  client/src/components/ChatContainer.jsx
  client/src/components/LoggedInUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/components/reactTranslit.js
  client/src/pages/MainPage.jsx
Labels: Project Task

#91 add SpeechToText dependency and add talk button to the chat container
  client/package-lock.json
  client/package.json
  client/src/components/ChatContainer.jsx
  client/src/components/STT.jsx
Labels: enhancement

#92 make update user request as 'patch', store id in redux state, set tok…
  client/src/components/LoggedInUserCard.jsx
  client/src/pages/SignInNew.jsx
  client/src/redux/UserReducer.js
Labels: enhancement

#93 make update user request as 'patch', store id in redux state, set tok…
  controllers/userController.js
  routes/apiRoutes/userRoutes/index.js
Labels: enhancement

#95 multiple commit
  client/src/components/LoggedInUserCard.jsx
  client/src/components/SearchedUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/components/UsersContainer.jsx
  controllers/authController.js
Labels: Project Task

#96 rearrange the order of execution
  index.js
Labels: CleanUp

#101 multiple commits
  client/public/index.html
  client/src/components/LoggedInUserCard.jsx
  client/src/components/MainFooter.js
  client/src/components/MainFooter.jsx
  client/src/components/UsersContainer.jsx
  client/src/pages/MainPage.jsx
Labels: CleanUp, enhancement

#103 cleanse and resolve react console issues
  client/src/components/LoggedInUserCard.jsx
  client/src/index.js
  client/src/pages/MainPage.jsx
  client/src/redux/index.js
Labels: CleanUp, bug, enhancement

#104 multiple changes
  client/src/components/ChatContainer.jsx
  client/src/components/FriendUserCard.jsx
  client/src/components/MainFooter.jsx
  client/src/components/UsersBox.jsx
  client/src/components/UsersContainer.jsx
  client/src/pages/MainPage.jsx
  client/src/redux/SelectedUserReducer.js
  client/src/redux/index.js
  controllers/userController.js
  models/User.js
  routes/apiRoutes/userRoutes/index.js
Labels: Project Task

#105 working private chat
  client/src/components/ChatContainer.jsx
  client/src/pages/MainPage.jsx
  controllers/userController.js
  index.js
Labels: Project Task

#107 Ability to click on + and add someone as friend
  client/src/components/MainFooter.jsx
  client/src/components/SearchedUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/components/UsersContainer.jsx
  client/src/pages/MainPage.jsx
  controllers/userController.js
  routes/apiRoutes/userRoutes/index.js
Labels: Project Task

#108 translation call in index, ability to remove friend
  client/src/components/FriendUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/components/UsersContainer.jsx
  controllers/messageController.js
  controllers/userController.js
  index.js
  routes/apiRoutes/userRoutes/index.js
Labels: Project Task

#109 add new state named friend removed
  client/src/components/UsersContainer.jsx
Labels: bug

#110 add github card to home page
  client/package-lock.json
  client/package.json
  client/src/pages/HomePage.jsx
Labels: Project Task

#112 adding chat
  client/src/components/ChatContainer.jsx
  client/src/components/divBar/ChatDivFrom.jsx
  client/src/components/divBar/ChatDivTo.jsx
Labels: good first issue

#113 from and to on chat container
  client/src/components/ChatContainer.jsx
Labels: enhancement

#111 change some style
  client/src/pages/HomePage.jsx
Labels: Project Task

#116 multiple commits mostly cleanse and pretty
  client/src/components/FriendUserCard.jsx
  client/src/components/LoggedInUserCard.jsx
  client/src/components/UsersBox.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/SignInNew.jsx
  index.js
Labels: CleanUp

#117 multiple cleanse commit
  client/src/assets/images/chype-new-black-trans-background.png
  client/src/assets/images/chype-new-white-background.png
  client/src/assets/images/chype-new-white-trans-background.png
  client/src/assets/images/chypeLogo-trans-olf.png
  client/src/assets/images/chypeLogo-trans.png
  client/src/assets/images/chypeShortLogo-trans.png
  client/src/assets/images/signInBg.jpg
  client/src/assets/images/signInBg1.jpg
  client/src/assets/images/y-trans.png
  client/src/assets/images/y.png
  client/src/components/AppBarMain.jsx
  client/src/components/FriendUserCard.jsx
  client/src/components/Navbar.jsx
  client/src/components/UsersContainer.jsx
  client/src/pages/HomePage.jsx
  index-old.js
Labels: CleanUp

#118 changes related to settings menu, setting page and set language
  client/src/components/Account.jsx
  client/src/components/ChatContainer.jsx
  client/src/components/General.jsx
  client/src/components/LoggedInUserCard.jsx
  client/src/pages/SettingsPage.jsx
Labels: CleanUp

#119 Abhi
  client/src/components/ChatContainer.jsx
  client/src/components/divBar/ChatDivFrom.jsx
  client/src/components/divBar/ChatDivTo.jsx
  client/src/components/divBar/DivBar.css
  client/src/pages/MainPage.jsx
  config/connection.js
  controllers/authController.js
  controllers/messageController.js
  controllers/userController.js
  db/schema.sql
  index.js
  models/User.js
  routes/apiRoutes/messageRoutes/index.js
Labels: Project Task

#120 add scroll to bottom dependency
  client/package-lock.json
  client/package.json
  client/src/components/ChatContainer.jsx
  client/src/pages/MainPage.jsx
Labels: Project Task

#121 remove scroll to bottom
  client/package-lock.json
  client/package.json
  client/src/components/ChatContainer.jsx
  index.js
Labels: CleanUp

#122 correct the package.json
  package.json
Labels: bug

#123 resolve package.json and package-lock.json
  package-lock.json
  package.json
Labels: bug

#124 Abhi
  README.md
  client/src/assets/images/Team.png
  client/src/assets/images/chatpage.png
  client/src/assets/images/poweredBy.PNG
  client/src/assets/images/signIn.png
Labels: documentation

#125 update team image in readme
  README.md
Labels: documentation

#126 code cleanup
  client/src/components/ChatContainer.jsx
  client/src/components/divBar/ChatDivFrom.jsx
  client/src/components/divBar/ChatDivTo.jsx
  client/src/pages/MainPage.jsx
  index.js
Labels: CleanUp

#127 some attempt to decorate homepage
  client/src/assets/images/ballonBackground.png
  client/src/pages/HomePage.jsx
Labels: CleanUp
